name: "Docker Build"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch: ~
  push:
    branches: [ master ]
  watch: # 3.手动点击收藏
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    name: docker build and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub # 第三步，登录docker hub
        uses: docker/login-action@v3  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          PGM_VERSION=$(python .github/get_version.py)
          docker buildx build \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            --platform "linux/amd64,linux/arm64/v8" \
            --build-arg "S6_ARCH=amd64" \
            --tag "${{ secrets.DOCKER_REPO }}:latest" \
            --tag "${{ secrets.DOCKER_REPO }}:${PGM_VERSION}" \
            -f Dockerfile \
            .
        
      - name: Push image # 第四步，推送镜像到docker hub 
        run: |
          docker push ${{ secrets.DOCKER_REPO }}:${PGM_VERSION}
